
version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - mynetwork
    depends_on:
      mariadb:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./files_db/instructions.sql:/docker-entrypoint-initdb.d/instructions.sql:ro
      - ./files_db/aAjouter.sql:/docker-entrypoint-initdb.d/02_aAjouter.sql:ro
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mynetwork:
    driver: bridge
