services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./files_db/instructions.sql:/docker-entrypoint-initdb.d/instructions.sql:ro
    networks:
      - mynetwork

  backend:
    build: .
    container_name: backend_container
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb_data:
